---
- name: get and install the python3 package manager (pip)
  apt: 
    name: python3-pip
    state: present
  become: yes

- name: get and install gns3-server
  pip:
    name: gns3-server
    version: "{{ gns3_ver }}"
    executable: pip3
    state: present
  notify:
  - restart gns3
  become: yes

- name: create /etc/gns3 directory
  file:
    path: /etc/gns3
    state: directory
  become: yes

- name: create gns3-server configuration file
  copy:
    src: gns3_server.conf
    dest: /etc/gns3/gns3_server.conf
  notify:
  - restart gns3
  become: yes

- name: create gns3 systemd unit file
  copy:
    src: gns3.service
    dest: /etc/systemd/system/gns3.service
  notify:
  - restart gns3
  become: yes

- name: enable and start gns3 service
  service:
    name: gns3
    enabled: yes
    state: started
  become: yes
...