---
- name: get and install qemu
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - qemu
      - qemu-kvm
  become: yes

- name: add gns3 user to kvm system group
  user:
    name: gns3
    groups: kvm
    append: yes
  become: yes
...
