---
- name: get and install subversion
  apt:
    name: subversion
    state: present
  become: yes

- name: subversion checkout for vpcs
  subversion:
    repo: svn://svn.code.sf.net/p/vpcs/code/trunk
    dest: "{{ src_dir }}/vpcs-code"
    force: yes

- name: perform a source-based install of vpcs
  script: install-vpcs.sh
  args:
    chdir: "{{ src_dir }}/vpcs-code/src"
    creates: /usr/local/bin/vpcs
...